### ISSUE TITLE
Windows Invalid Format String

### ISSUE THREAD

**Issue by visch** [hotgluexyz/target-csv#1]
```
Traceback (most recent call last):
  File "C:\Python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\VISCHDW\Desktop\code\d11co\meltano\.meltano\loaders\target-csv\venv\Scripts\target-csv.exe\__main__.py", line 7, in <module>
  File "c:\users\vischdw\desktop\code\d11co\meltano\.meltano\loaders\target-csv\venv\lib\site-packages\target_csv.py", line 149, in main
    state = persist_messages(config.get('delimiter', ','),
  File "c:\users\vischdw\desktop\code\d11co\meltano\.meltano\loaders\target-csv\venv\lib\site-packages\target_csv.py", line 52, in persist_messages
    o = singer.parse_message(message).asdict()
  File "c:\users\vischdw\desktop\code\d11co\meltano\.meltano\loaders\target-csv\venv\lib\site-packages\singer\messages.py", line 63, in asdict
    result['time_extracted'] = u.strftime(as_utc)
  File "c:\users\vischdw\desktop\code\d11co\meltano\.meltano\loaders\target-csv\venv\lib\site-packages\singer\utils.py", line 43, in strftime
    dt_str = dtime.strftime(format_str)
ValueError: Invalid format string
```

Seems similar to https://github.com/transferwise/pipelinewise-tap-oracle/pull/14

**Comment by visch** [comment]
Bumped the singer version, but I"m running into issues with meltano running custom plugins on Windows right this moment bear with me :D

**Comment by hsyyid** [comment]
@visch Thanks for the contribution! Will review shortly.
